name: micro-services
services:
  db-xml:
    container_name: db-xml
    build: docker/images/db/xml_db
    volumes:
      - postgres-data-xml:/var/lib/postgresql/data/
    ports:
      - "1001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 30
  db-rel:
    container_name: db-rel
    build: docker/images/db/rel_db
    volumes:
      - postgres-data-rel:/var/lib/postgresql/data/
    ports:
      - "1002:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 30


  rpc-server:
    container_name: rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - db-xml
    environment:
      - USE_DEV_MODE=true
  rpc-client:
    container_name: rpc-client
    build: docker/images/python
    stdin_open: true
    volumes:
      - "./src/rpc-client:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server
    environment:
      - USE_DEV_MODE=$USE_DEV_MODE
  migrator:
    container_name: db-migrator
    build: docker/images/python
    volumes:
      - "./src/migrator:/app"
    entrypoint: ["sh", "-c", "chmod +x ./run.sh && ./run.sh"]

  api-entities:
    container_name: api
    build: docker/images/javascript
    volumes:
      - "./src/api-entities:/app"




volumes:
  postgres-data-xml:
  postgres-data-rel:

