services:

  db:
    container_name: is-db
    build: docker/images/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  rpc-server:
    container_name: is-rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/app"
    depends_on:
      - db
    environment:
      - USE_DEV_MODE=true

  rpc-client:
    container_name: is-rpc-client
    build: docker/images/python
    stdin_open: true
    volumes:
      - "./src/rpc-client:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server
    environment:
      - USE_DEV_MODE=$USE_DEV_MODE

  sample-db-access:
    container_name: is-db-access
    build: docker/images/python
    volumes:
      - "./src/samples/db-access:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

  sample-xml-generation:
    container_name: is-xml-generation
    build: docker/images/python
    volumes:
      - "./src/samples/xml-generation:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

volumes:
  postgres_data: