services:

  xml_db:
    container_name: is-xml_db
    build: docker/images/db/xml_db
    volumes:
      - postgres_data_xml_db:/var/lib/postgresql/data/
    ports:
      - "1:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 30

  rel_db:
    container_name: is-rel_db
    build: docker/images/db/rel_db
    volumes:
      - postgres_data_rel_db:/var/lib/postgresql/data/
    ports:
      - "2:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 30

  rpc-server:
    container_name: is-rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - xml_db
    environment:
      - USE_DEV_MODE=true

  rpc-client:
    container_name: is-rpc-client
    build: docker/images/python
    stdin_open: true
    volumes:
      - "./src/rpc-client:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server
    environment:
      - USE_DEV_MODE=$USE_DEV_MODE

  migrator:
    container_name: db-migrator
    build: docker/images/python
    volumes:
      - "./src/migrator:/app"
    entrypoint: ["sh", "-c", "chmod +x ./run.sh && ./run.sh"]


volumes:
  postgres_data_xml_db:
  postgres_data_rel_db: